name: example
description: Example
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  code_text_field:
    path: ../

flutter:
  uses-material-design: true
  fonts:
    - family: SourceCode
      fonts:
        - asset: assets/fonts/sourceCode/SourceCodePro-Black.ttf
          weight: 900
        - asset: assets/fonts/sourceCode/SourceCodePro-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/sourceCode/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/sourceCode/SourceCodePro-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/sourceCode/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sourceCode/SourceCodePro-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/sourceCode/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/sourceCode/SourceCodePro-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/sourceCode/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/sourceCode/SourceCodePro-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/sourceCode/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/sourceCode/SourceCodePro-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/sourceCode/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sourceCode/SourceCodePro-ExtraLightItalic.ttf
          style: italic
          weight: 200
